
# jdbc.driver=com.mysql.cj.jdbc.Driver
# jdbc.url=jdbc:mysql://it119kr.asuscomm.com:3306/project
# jdbc.user=project
# jdbc.pwd=pt^VJjrV~g


spring:
    application:
        name : saintkream

    datasource:
        url: jdbc:mysql://it119kr.asuscomm.com:3306/project
        username: project
        password: pt^VJjrV~g
        driver-class-name: com.mysql.cj.jdbc.Driver

    # 정적 파일(이미지, CSS, JS 등)을 URL로 접근할 수 있도록 설정하는 옵션입니다.
    # http://localhost:8080/{파일명}
    web:
        resources:
            # static-locations: file:D:/upload/    
            static-locations: classpath:/static/  
    # security:
    #   oauth2:
    #     client:
    #       registration:
    #         kakao:
    #           client-id: c511457645936818e2db5ecdc890dc9d
    #           client-secret: UK5yf3VgXmUWsbSzwaTLRFVMJNXg6ggL
    #           redirect-uri: http://localhost:8080/login/oauth2/code/kakao
    #           authorization-grant-type: authorization_code
    #           client-authentication-method: client_secret_post
    #           client-name: Kakao
    #           scope:
    #             - profile_nickname
    #             - profile_image
    #             - account_email
    #         naver:
    #           client-id: jOeGSWAwUdbzfiBC8hCb
    #           client-secret:  4zW6PNY6rJ
    #           redirect-uri: http://localhost:8080/login/oauth2/code/naver
    #           authorization-grant-type: authorization_code
    #           client-name: Naver
    #           scope:
    #             - name
    #             - email
    #       provider:
    #         kakao:
    #           authorization-uri: https://kauth.kakao.com/oauth/authorize
    #           token-uri: https://kauth.kakao.com/oauth/token
    #           user-info-uri: https://kapi.kakao.com/v2/user/me
    #           user-name-attribute: id
    #         naver:
    #           authorization-uri: https://nid.naver.com/oauth2.0/authorize
    #           token-uri: https://nid.naver.com/oauth2.0/token
    #           user-info-uri: https://openapi.naver.com/v1/nid/me
    #           user-name-attribute: response





# 파일 업로드 기능에서 파일이 저장될 물리적 경로를 명시.              
file:
  upload-dir: D:/upload

server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.saintkream.server

# 비밀키 사용(32바이트길이)  
# 1 시간 = 1000ms * 60 * 60 ;
jwt:
  secret : "abcdASDF1234abcdQWER0987poiuPOIU"
  expiration : 3600000