spring:
  application:
    name: saintkream

  datasource:
    url: jdbc:mysql://it119kr.asuscomm.com:3306/final
    username: project
    password: pt^VJjrV~g
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      # 정적 파일 경로
      static-locations: classpath:/static/

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: aa7eda2ca1e3eaf116b2de1779549d6f
            client-secret: VBrOMxbJ1xCFC8gpRmYxtz2QHKfRwYjR
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            #redirect-uri: http://localhost:3000/register
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

          naver:
            client-id: GRe9UrA37wkvqy_g4DkS
            client-secret: nTKHK150YY
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            #redirect-uri: http://localhost:3000/register
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email

          google:
            client-id: 286712382149-rtu35b1vj6saab56a9rflfc0bun2v2sn.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            #redirect-uri: http://localhost:3000/register
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Google
            scope:
              # - openid  // 이거쓰면 다른 애들이랑 provider 구분이 안됨
              - profile
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

       

file:
  # 파일 업로드 경로
  upload-dir: D:/upload

server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.saintkream.server
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # JWT 비밀키 및 만료 시간 설정
  secret: "abcdASDF1234abcdQWER0987poiuPOIU"
  expiration: 3600000


logging:
  level:
    root: info
    org.apache.ibatis: debug
    org.mybatis: debug